### ISSUE TITLE
Gem seems to have a problem with Rails 5

### ISSUE THREAD

**Issue by 0bserver07** [vigetlabs/olive_branch#8]
Set:

`Rails 5.0.1.alpha`
`Json-resource-api`

only Rails API:

Stacktrace:

```
.rvm/gems/ruby-2.3.1/bundler/gems/rails-2b4a9735d816/actionpack/lib/action_dispatch/middleware/stack.rb:35:in `build': undefined method `new' for "OliveBranch::Middleware":String (NoMethodError)
Did you mean?  next
       	from /Users/yad/.rvm/gems/ruby-2.3.1/bundler/gems/rails-2b4a9735d816/actionpack/lib/action_dispatch/middleware/stack.rb:99:in `block in build'
       	from /Users/yad/.rvm/gems/ruby-2.3.1/bundler/gems/rails-2b4a9735d816/actionpack/lib/action_dispatch/middleware/stack.rb:99:in `each'
       	from /Users/yad/.rvm/gems/ruby-2.3.1/bundler/gems/rails-2b4a9735d816/actionpack/lib/action_dispatch/middleware/stack.rb:99:in `inject'
       	from /Users/yad/.rvm/gems/ruby-2.3.1/bundler/gems/rails-2b4a9735d816/actionpack/lib/action_dispatch/middleware/stack.rb:99:in `build'
       	from /Users/yad/.rvm/gems/ruby-2.3.1/bundler/gems/rails-2b4a9735d816/railties/lib/rails/engine.rb:508:in `block in app'
       	from /Users/yad/.rvm/gems/ruby-2.3.1/bundler/gems/rails-2b4a9735d816/railties/lib/rails/engine.rb:504:in `synchronize'
       	from /Users/yad/.rvm/gems/ruby-2.3.1/bundler/gems/rails-2b4a9735d816/railties/lib/rails/engine.rb:504:in `app'
```

**Comment by daniel-nelson** [comment]
@0bserver07 It's just an issue with the README. Remove the quotes in the line
```config.middleware.use "OliveBranch::Middleware"```
so that it becomes
```config.middleware.use OliveBranch::Middleware```
